### ISSUE TITLE
 Failed to load function afkannouncer:afk_kick/announce_afk_kick

### ISSUE THREAD

**Issue by bearaujus** [jodeks-datapacks/AFK-Announcer#4]
I downloaded the datapack and install on the server side.
But during my server initialization I got this error

```
Sep 29 23:39:53 server bash[1336143]: [23:39:53] [main/ERROR]: Failed to load function afkannouncer:afk_kick/announce_afk_kick
Sep 29 23:39:53 server bash[1336143]: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown or incomplete command, see below for error at position 0: <--[HERE]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Sep 29 23:39:53 server bash[1336143]: Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown or incomplete command, see below for error at position 0: <--[HERE]
Sep 29 23:39:53 server bash[1336143]:         at net.minecraft.class_2158.method_9195(class_2158.java:80) ~[server-intermediary.jar:?]
Sep 29 23:39:53 server bash[1336143]:         at net.minecraft.class_5349.method_29451(class_5349.java:89) ~[server-intermediary.jar:?]
Sep 29 23:39:53 server bash[1336143]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
Sep 29 23:39:53 server bash[1336143]:         ... 6 more
```

Or can you put description that describe should I install the mod and datapack on the server side at the same time? or I just need to install the datapack only? (*Im very newbie at this)

Thank you!

**Comment by Jodekq** [comment]
Hey there!
You only need to install either the mod or the datapack. (I suggest the datapack)
To fix the error, you probably have to set the function-permission-level to 3 in the server.properties

**Comment by bearaujus** [comment]
I already set to 4 (owner) it should be have higher privilege than 3 (admin) [ref](https://minecraft.fandom.com/wiki/Permission_level#:~:text=In%20Java%20Edition%2C%20permission%20level,has%20permission%20level%20of%204.)
![image](https://github.com/user-attachments/assets/d9c3adbf-35b0-4dc4-bfed-c007572dd4d3)

Also, are these mods probably make this repository broken? since this is my current datapacks and mods:
```
  version: '1.21.1'
  java-url: 'https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz'
  jar-url: 'https://meta.fabricmc.net/v2/versions/loader/1.21.1/0.16.5/1.0.1/server/jar'

  mod-urls:
    - 'https://cdn.modrinth.com/data/P7dR8mSH/versions/qKPgBeHl/fabric-api-0.104.0%2B1.21.1.jar'
    - 'https://cdn.modrinth.com/data/Vebnzrzj/versions/l47d4ZWk/LuckPerms-Fabric-5.4.140.jar'
    - 'https://cdn.modrinth.com/data/zQhsx8KF/versions/3s91GEhG/servux-fabric-1.21.0-0.3.7.jar'
    - 'https://cdn.modrinth.com/data/fdZkP5Bb/versions/pDaHPTD2/vanilla-permissions-0.2.4%2B1.21.1.jar'
  data-pack-urls:
    - 'https://cdn.modrinth.com/data/hXdoMWYD/versions/bER7Y4gB/ShowDimensionInName-%5B1.21%5D-v.2.4.0.zip'
    - 'https://cdn.modrinth.com/data/hxaUKE37/versions/J4OLXp9O/player%20health%20indicator%201.21%20v4.zip'
    - 'https://cdn.modrinth.com/data/3rfGELpR/versions/mitsYHCY/dimension-messsages_1.21.zip'
    - 'https://cdn.modrinth.com/data/26qk5hxQ/versions/VHmpTVeX/AFK%20Announcer-%5B1.21%5D-v.2.4.2.zip'
```

**Comment by bearaujus** [comment]
Yay it's working now, thank you!
```
Sep 30 00:15:09 server bash[1344681]: [00:15:09] [Worker-Main-3/INFO]: Loaded Fabric Permissions
Sep 30 00:15:09 server bash[1344681]: [00:15:09] [main/INFO]: Loaded 1290 recipes
Sep 30 00:15:09 server bash[1344681]: [00:15:09] [main/INFO]: Loaded 1406 advancements
Sep 30 00:15:10 server bash[1344681]: [00:15:10] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.086 ms
Sep 30 00:15:10 server bash[1344681]: [00:15:10] [Server thread/INFO]:         __
Sep 30 00:15:10 server bash[1344681]: [00:15:10] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.140
Sep 30 00:15:10 server bash[1344681]: [00:15:10] [Server thread/INFO]:   |___ |      Running on Fabric - fabric@0.104.0+1.21.1
Sep 30 00:15:10 server bash[1344681]: [00:15:10] [Server thread/INFO]:
Sep 30 00:15:10 server bash[1344681]: [00:15:10] [Server thread/INFO]: Loading configuration...
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Loading storage provider... [H2]
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Loading internal permission managers...
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Performing initial data load...
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Successfully enabled. (took 1110ms)
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Starting minecraft server version 1.21.1
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Loading properties
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Default game type: CREATIVE
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Generating keypair
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25566
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Using epoll channel type
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Preparing level "world"
Sep 30 00:15:11 server bash[1344681]: [00:15:11] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
Sep 30 00:15:12 server bash[1344681]: [00:15:12] [Worker-Main-6/INFO]: Preparing spawn area: 0%
Sep 30 00:15:12 server bash[1344681]: [00:15:12] [Server thread/INFO]: Time elapsed: 365 ms
Sep 30 00:15:12 server bash[1344681]: [00:15:12] [Server thread/INFO]: Done (0.618s)! For help, type "help"
```

**Comment by bearaujus** [comment]
Conclusion:
When you execute
```
$JAVA_PATH -Xms$JAVA_XMS -Xmx$JAVA_XMX -jar $SERVER_JAR_PATH -initSettings
```

The default value for `function-permission-level` on `server.properties` is set to `2`.
What you need to do is adjust the `function-permission-level` to `3` or higher! [Ref](https://minecraft.fandom.com/wiki/Permission_level#:~:text=In%20Java%20Edition%2C%20permission%20level,has%20permission%20level%20of%204.)
